In [7]:
import pandas as pd

df = pd.read_csv("rgb-v5_eval_results.csv")
#df[df["env"] == "Skiing"].sort_values(by=["reward_mean"])
df
#df = df.drop(df[(df.score < 50) & (df.score > 20)].index)
#df[df["env"] == "Pong"]

,Unnamed: 0,env,variant,train_seed,eval_seed,episodes,reward_mean,reward_std,steps_mean,steps_std
0,0,Seaquest,rgbv5,32,789,5,752.0,135.410490,2025.4,282.014610
1,1,Seaquest,rgbv5,32,123,5,780.0,87.635610,2093.2,147.515965
2,2,Seaquest,rgbv5,32,1011,5,820.0,116.619040,2160.2,175.671739
3,3,Seaquest,rgbv5,32,456,5,824.0,64.992310,2156.8,93.188841
4,4,Seaquest,rgbv5,16,123,5,884.0,19.595919,2269.0,0.000000
5,5,Seaquest,rgbv5,16,789,5,876.0,8.000000,2267.4,3.200000
6,6,Seaquest,rgbv5,16,456,5,880.0,12.649111,2269.0,0.000000
7,7,Seaquest,rgbv5,16,1011,5,876.0,14.966630,2269.0,0.000000
8,8,Seaquest,rgbv5,0,123,5,784.0,57.131428,2008.2,148.408086
9,9,Seaquest,rgbv5,0,456,5,824.0,95.833190,2113.8,241.679457
10,10,Seaquest,rgbv5,0,1011,5,864.0,54.258640,2171.6,120.252401
11,11,Seaquest,rgbv5,0,789,5,884.0,38.781440,2231.6,70.867764
12,12,Kangaroo,rgbv5,32,123,5,600.0,0.000000,507.0,4.604346
13,13,Kangaroo,rgbv5,32,456,5,600.0,0.000000,500.2,3.655133
14,14,Kangaroo,rgbv5,32,1011,5,600.0,0.000000,501.0,3.521363
15,15,Kangaroo,rgbv5,32,789,5,600.0,0.000000,503.2,4.354308
16,16,Kangaroo,rgbv5,16,123,5,1200.0,0.000000,608.0,2.683282
17,17,Kangaroo,rgbv5,16,456,5,1160.0,80.000000,610.8,1.469694
18,18,Kangaroo,rgbv5,16,789,5,1160.0,80.000000,605.4,7.709734
19,19,Kangaroo,rgbv5,16,1011,5,1160.0,80.000000,610.2,7.600000
20,20,Kangaroo,rgbv5,0,123,5,600.0,0.000000,462.0,1.897367
21,21,Kangaroo,rgbv5,0,456,5,600.0,0.000000,461.2,1.469694
22,22,Kangaroo,rgbv5,0,789,5,600.0,0.000000,462.6,2.332381
23,23,Kangaroo,rgbv5,0,1011,5,600.0,0.000000,463.0,1.897367
24,24,Asterix,rgbv5,32,123,5,2180.0,520.192260,948.0,259.786836
25,25,Asterix,rgbv5,32,456,5,2100.0,554.075800,851.0,198.910030
26,26,Asterix,rgbv5,32,1011,5,2230.0,584.465600,871.2,228.613560
27,27,Asterix,rgbv5,32,789,5,2140.0,467.332860,969.4,96.593167
28,28,Asterix,rgbv5,16,123,5,2350.0,319.374400,826.0,110.252438
29,29,Asterix,rgbv5,16,456,5,2320.0,290.860780,802.4,46.846985
30,30,Asterix,rgbv5,16,789,5,2190.0,361.109400,762.4,112.199109
31,31,Asterix,rgbv5,16,1011,5,1900.0,419.523530,742.0,232.149090
32,32,Asterix,rgbv5,0,123,5,1970.0,434.281000,789.8,201.992475
33,33,Asterix,rgbv5,0,456,5,1900.0,407.430970,788.8,146.011506
34,34,Asterix,rgbv5,0,1011,5,2050.0,584.807700,914.2,295.287250
35,35,Asterix,rgbv5,0,789,5,2190.0,560.713800,981.0,331.444113
36,36,Bowling,rgbv5,16,123,5,154.0,0.000000,1568.0,0.000000
37,37,Bowling,rgbv5,16,456,5,154.0,0.000000,1568.0,0.000000
38,38,Bowling,rgbv5,16,789,5,154.0,0.000000,1568.0,0.000000
39,39,Bowling,rgbv5,16,1011,5,154.0,0.000000,1547.2,41.600000
40,40,Bowling,rgbv5,32,123,5,68.4,3.200000,2103.8,15.600000
41,41,Bowling,rgbv5,32,456,5,70.0,0.000000,2096.0,0.000000
42,42,Bowling,rgbv5,32,789,5,68.2,2.227106,2103.4,9.329523
43,43,Bowling,rgbv5,0,123,5,86.0,0.000000,1880.0,0.000000
44,44,Bowling,rgbv5,0,456,5,86.0,0.000000,1880.0,0.000000
45,45,Bowling,rgbv5,0,789,5,86.0,0.000000,1880.0,0.000000
46,46,Bowling,rgbv5,0,1011,5,84.0,4.000000,1900.8,41.600000
47,47,Bowling,rgbv5,32,1011,5,61.6,16.800000,7076.4,9960.800000
48,48,Tennis,rgbv5,32,123,5,-1.0,0.000000,26998.0,0.000000
49,49,Tennis,rgbv5,32,456,5,-0.8,0.400000,26998.0,0.000000
50,50,Tennis,rgbv5,32,789,5,-1.0,0.000000,26998.0,0.000000
51,51,Tennis,rgbv5,32,1011,5,-1.0,0.000000,26998.0,0.000000

In [8]:
grouped = df.groupby(["env", "variant"])

agg_df = grouped["reward_mean"].agg(["mean", "std"])
agg_df

                         mean         std
env      variant
Asterix  rgbv5    2126.666667  148.589326
Bowling  rgbv5     102.183333   39.121206
Kangaroo rgbv5     790.000000  280.842887
Seaquest rgbv5     837.333333   46.658008
Tennis   rgbv5      -0.950000    0.100000

In [9]:
agg_df.index = agg_df.index.set_levels(agg_df.index.levels[1].str.replace('rgbv4', 'original'), level=1)
agg_df.to_csv("agg_results.csv")