In [6]:
import pandas as pd

df = pd.read_pickle("eval_results.pkl")
df[df["env"] == "Freeway"].sort_values(by=["reward_mean"])
#df = df.drop(df[(df.score < 50) & (df.score > 20)].index)
#df[df["env"] == "Pong"]

,env,variant,train_seed,eval_seed,episodes,reward_mean,reward_std,steps_mean,steps_std
119,Freeway,iscobots,16,1011,5,0.000000,0.000000,2048.0,0.0
117,Freeway,iscobots,16,456,5,0.000000,0.000000,2048.0,0.0
116,Freeway,iscobots,16,123,5,0.000000,0.000000,2048.0,0.0
118,Freeway,iscobots,16,789,5,0.000000,0.000000,2048.0,0.0
115,Freeway,iscobots,0,1011,5,27.000000,1.673320,2048.0,0.0
112,Freeway,iscobots,0,123,5,27.000000,2.097618,2048.0,0.0
113,Freeway,iscobots,0,456,5,28.400000,1.019804,2048.0,0.0
114,Freeway,iscobots,0,789,5,28.799999,1.720465,2048.0,0.0
110,Freeway,iscobots,32,789,5,30.200001,0.748331,2048.0,0.0
111,Freeway,iscobots,32,1011,5,30.600000,0.489898,2048.0,0.0
109,Freeway,iscobots,32,456,5,30.600000,0.800000,2048.0,0.0
108,Freeway,iscobots,32,123,5,30.600000,0.800000,2048.0,0.0
103,Freeway,scobots,32,1011,5,31.400000,0.489898,2048.0,0.0
96,Freeway,scobots,0,123,5,31.600000,0.489898,2048.0,0.0
101,Freeway,scobots,32,456,5,31.600000,0.489898,2048.0,0.0
98,Freeway,scobots,0,789,5,31.600000,0.489898,2048.0,0.0
102,Freeway,scobots,32,789,5,31.799999,0.400000,2048.0,0.0
97,Freeway,scobots,0,456,5,31.799999,0.400000,2048.0,0.0
105,Freeway,scobots,16,456,5,32.000000,0.000000,2048.0,0.0
104,Freeway,scobots,16,123,5,32.000000,0.000000,2048.0,0.0
100,Freeway,scobots,32,123,5,32.000000,0.000000,2048.0,0.0
99,Freeway,scobots,0,1011,5,32.000000,0.000000,2048.0,0.0
106,Freeway,scobots,16,789,5,32.000000,0.000000,2048.0,0.0
107,Freeway,scobots,16,1011,5,32.000000,0.000000,2048.0,0.0

In [5]:
grouped = df.groupby(["env", "variant"])

grouped["reward_mean"].agg(["mean", "std"])

                          mean         std
env      variant
Asterix  iscobots  1746.666626  216.724934
         rgb         24.854546    4.160310
         scobots    597.500000  304.604811
Bowling  rgb         10.000000    0.000000
Freeway  rgb         32.555557    0.409607
Kangaroo iscobots  1790.000000   54.272042
         rgb          2.093333    0.700213
         scobots    218.333328  113.284303
Pong     rgb         -0.383333    3.070633